services:
  - type: web
    name: realnex-chatbot
    env: python
    plan: free
    buildCommand: bash install_tesseract.sh && pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app
    envVars:
      - key: XAI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.9
